# check your version: https://docs.docker.com/compose/compose-file/
version: "3.7"

services:
    # first container
    backend:
        # look for dockerfile and build the container
        build:
            context: ./server
            target: production
        container_name: backend
        restart: always
        networks:
            - bikescience_network
        # set environment variables
        environment:
            - APP_NAME=FlaskApp
        #  mount the volumes so we can change code and hot reload
        volumes:
            - './server:/backend'
        #  expose port on the container, only to other containers
        expose:
            - 9000

    ui:
        build: ./bsweb
        container_name: ui
        restart: always
        networks:
            - bikescience_network
        expose:
            - 80

    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        networks:
            - bikescience_network
        # port allows the host machine to link to container
        # pass 80 from host machine to 80 of the image filesystem
        ports:
            - "80:80"

    postgres:
        build: ./server/bikesp/postgres
        container_name: bikesp_dw
        environment:
            POSTGRES_DB: bikesp_science
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        networks:
            - bikescience_network
        expose:
            - 5432
        volumes:
            - pg_data:/var/lib/postgresql/data 
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d bikesp_science"]
            interval: 5s
            timeout: 5s
            retries: 5

volumes:
  pg_data:

networks:
    bikescience_network:
        name: bikescience_network
        driver: bridge
