FROM python:3.6-stretch

RUN mkdir /backend
WORKDIR /backend

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 5000
ENV PYTHONPATH="${PYTHONPATH}:/backend"
CMD flask run --host=0.0.0.0 --port=5000
