# check your version: https://docs.docker.com/compose/compose-file/
version: "3.9"

# Docker compose for development environment
services:
  backend:
    build:
      context: .
      target: development
    container_name: backend_dev
    restart: always
    environment:
      - FLASK_APP=app.py
      - APP_NAME=FlaskApp
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    volumes:
      - './:/backend'
    ports:
      - "5000:5000"
