# check your version: https://docs.docker.com/compose/compose-file/
version: "3.9"

# Docker compose for debugging with vs code
services:
  server:
    build:
      context: .
      target: debug
    container_name: backend_debug
    environment:
      - FLASK_APP=app.py
      - APP_NAME=FlaskApp
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    volumes:
      - './:/backend'
    ports:
      - 5000:5000
      - 5678:5678